Velocity SIMD CPU Runtime
m4rs-mt/ILGPU pull request #1055
Opened 2023-08-24 19:34 UTC by m4rs-mt

This PR adds the announced SIMD-based CPU runtime fully implemented in managed code. The new `Velocity` accelerator supports most GPU kernels (except those using dynamic shared memory) and is able to utilize SIMD hardware acceleration on modern CPUs, allowing you to run your ILGPU kernels efficiently on then CPU by leveraging the implemented automatic vectorization engine.

It supports the following hardware configurations:

- Scalar version simulating warps of length 2 (available)
- `128bit`-based `X64 SSE` and `ARM64 Neon` instructions (also supports `M1` Macs - #769, in progress)
- `256bit`-based `X64 AVX` instructions (in progress)
- `512bit`-based `X64 AVX2` instructions (limited feature set; some functions will fallback to `256bit` registers)

*Note that this PR is a new version of PR #891*.

2023-09-12 12:54 UTC, MoFtZ requested changes
ISSUE: `VelocityUnaryFloatOperations`, `IsPredicate64` tests are failing.

![image](https://github.com/m4rs-mt/ILGPU/assets/27792737/8a4460fb-28ae-4457-ba8d-22e027f929f2)

`address.item1` = 1
`value.item1` = 1

`  System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
---- System.NullReferenceException : Object reference not set to an instance of an object.
`

Tested on Intel Core i7-7700.

2023-09-12 12:54 UTC, MoFtZ commented on Src/ILGPU.Tests.Velocity/ILGPU.Tests.Velocity.csproj
> +    <PackageReference Include="xunit" Version="2.5.0" />
ISSUE: Missing `xunit.runner.visualstudio` nuget package. This prevents the Velocity tests from being discovered in Visual Studio.

2023-09-12 14:03 UTC, m4rs-mt commented
@MoFtZ That is unexpected and should clearly not happen. Let me try to replicate that.

2023-09-13 11:27 UTC, MoFtZ commented
> @MoFtZ That is unexpected and should clearly not happen. Let me try to replicate that.

Based on #1096 and https://github.com/m4rs-mt/ILGPU/actions/runs/6168945265/job/16742300692?pr=1096, it looks like the issue is affecting Windows, but not Ubuntu?

2023-09-13 15:11 UTC, m4rs-mt commented
I can confirm that this issue does not appear on Ubuntu x64/arm64 and on MacOS arm64.

2023-09-26 13:55 UTC, m4rs-mt commented
@MoFtZ I addressed an issue in the `ScalarX2` code generator which know passes all tests on Windows/Intel x64.

2023-09-27 11:11 UTC, MoFtZ approved these changes

2023-09-27 11:40 UTC, merged