Towards API/ABI stability + refinement of AcceleratorId + ContextFlags.
m4rs-mt/ILGPU pull request #428
Opened 2021-03-03 19:41 UTC by m4rs-mt

We are aiming for API/ABI stability in v1.0. Therefore it is a good time to replace the (mostly obsolete) enumeration `ContextFlags`. In addition, there were also many questions and issue reports from the community about supported and detected accelerators (especially related to the `OpenCL` accelerator). Related to these detection issues, there are also some reports about freezing calls to the `OpenCL` runtime API even though users only want to use the `CPU`/`Cuda` accelerators.

This PR removes the enumeration `ContextFlags` and implements the same functionality in an object oriented way using a `Context.Builder` class. It offers a fluent-API like configuration interface which makes it easy to set up:
```c#
// Enables all supported accelerators (default CPU accelerator only) and puts the context
// into auto-assertion mode via "AutoAssertions()". In other words, if a debugger is attached,
// the `Context` instance will turn on all assertion checks. This behavior is identical
// to the current implementation via new Context();
using var context = Context.CreateDefault();

// Turns on O2 and enables all compatible Cuda devices.
using var context = Context.Create(builder =>
{
    builder.Optimize(OptimizationLevel.O2).Cuda();
});

// Turns on all assertions, enables the IR verifier and enables all compatible OpenCL
devices.
using var context = Context.Create(builder =>
{
    builder.Assertions().Verify().OpenCL();
});

// Turns on kernel source-line annotations, fast math using 32-bit float and enables
// *all* (even incompatible) OpenCL devices.
using var context = Context.Create(builder =>
{
    builder
        .DebugSymbols(DebugSymbolsMode.KernelSourceAnnotations)
        .Math(MathMode.Fast32BitOnly)
        .OpenCL(device => true);
});

// Selects an OpenCL device with a warp size of at least 32:
using var context = Context.Create(builder =>
{
    builder.OpenCL(device => device.WarpSize >= 32);
});

// Turns on all assertions in debug mode (same behavior like calling CreateDefault()):
using var context = Context.Create(builder =>
{
    builder.AutoAssertions();
});

// Turns on debug optimizations (level O0) and all assertions if a debugger is attached:
using var context = Context.Create(builder =>
{
    builder.AutoDebug();
});

// Turns on debug mode (optimization level P0, assertions and kernel debug information):
using var context = Context.Create(builder =>
{
    builder.Debug();
});

// Disable caching, enable conservative inlining and inline mutable static field values:
using var context = Context.Create(builder =>
{
    builder
        .Caching(CachingMode.Disabled)
        .Inlining(InliningMode.Conservative)
        .StaticFields(StaticFieldMode.MutableStaticFields);
});

// Turn on *all* CPU accelerators that simulate different hardware platforms:
using var context = Context.Create(builder => builder.CPU());

// Turn on an AMD-based CPU accelerator:
using var context = Context.Create(builder => builder.CPU(CPUDeviceKind.AMD));
```
Note that by default all debug symbols are automatically turned off when a debugger is attached. If you want to turn on the debug information in all cases, call `.builder.DebugSymbols(DebugSymbolsMode.Basic)`. At the same time, this PR introduces the notion of `Device`, which replaces the implementation of `AcceleratorId`. This allows us to query detailed device information without explicitly instantiating an accelerator instance:
```c#
// Print all device information without instantiating a single accelerator
// (device context) instance.
using var context = Context.Create(...);
foreach (var device in context)
{
    // Print detailed accelerator information
    device.PrintInformation();

    // ...
}
```

Note that this PR removes the ability to call the accelerator constructors (e.g. `new CudaAccelerator(...)`) directly. Either use the `CreateAccelerator` methods defined in the `Device` classes or use one of the extension methods like `CreateCudaAccelerator(...)` of the `Context` class itself:
```c#
using var context = Context.Create(...);
foreach (var device in context)
{
    // Instantiate an accelerator instance on this device
    using Accelerator accel = device.CreateAccelerator();
    // ...
}

// Instantiate the 2nd Cuda accelerator (NOTE that this is the *2nd* Cuda device
// and *not* the 2nd device of your machine).
using CudaAccelerator cudaDevice = context.CreateCudaAccelerator(1);

// Instantiate the 1st OpenCL accelerator (NOTE that this is the *1st* OpenCL device
// and *not* the 1st device of your machine).
using CLAccelerator clDevice = context.CreateOpenCLAccelerator(0);
```

`Context` properties that expose types from other (ILGPU internal) namespaces that cannot/should not (?) be covered by the API/ABI guarantees we want to give, has been made `internal` properties. To access these properties, use one of the available extension methods located in the corresponding namespaces:
```c#
using var context = ...

// OLD way
var internalIRContext = context.IRContext;

// NEW way:
// using namespace ILGPU.IR;
var internalIRContext = context.GetIRContext();
```

2021-03-04 11:00 UTC, MoFtZ requested changes

2021-03-04 20:19 UTC, m4rs-mt commented on Src/ILGPU/Runtime/Cuda/CudaDevice.cs
> +            Backend.EnsureRunningOnPlatform(TargetPlatform.X64);
@MoFtZ You are right. We have already introduced the UVA features for unified addresses, which work only on 64-bit machines. Therefore, we should disable the X86 Cuda support.

2021-03-04 20:23 UTC, m4rs-mt commented on Src/ILGPU/Runtime/Accelerator.cs
> +        protected Accelerator(Context context, Device device)
I am not sure. An `Accelerator` implements `IDevice` in order to share common properties and extension methods with the `Device` class. However, an accelerator should not be instantiated using another `Accelerator` to my mind.

2021-03-11 21:04 UTC, m4rs-mt commented on Src/ILGPU/ContextProperties.cs
> +        Default,
The problem with these enumeration values in general is that we cannot change them again due to ABI compatibility constraints. Maybe we should rename `Default` to `Aggressive`.

2021-03-11 21:07 UTC, m4rs-mt commented on Src/ILGPU/Backends/PTX/PTXArchitecture.cs
> +        public static bool TryGetArchitecture(
Makes sense. I am going to move them to the `Cuda` namespace.

2021-03-11 21:09 UTC, m4rs-mt commented on Src/ILGPU/Backends/PTX/PTXArchitecture.cs
> +                architecture <= PTXArchitecture.SM_86;
What do you suggest? Skip the second check against `SM_86`?

2021-03-11 21:12 UTC, m4rs-mt commented on Src/ILGPU/Backends/PTX/PTXBackend.cs
> +            bool useDebugInfo = debugSymbolsMode > DebugSymbolsMode.Kernel;
Nice one 👍

2021-03-11 21:14 UTC, m4rs-mt commented on Src/ILGPU/Context.Builder.cs
> +            public DeviceRegistry AcceleratorRegistry { get; } =
👍 let's change its visibility to `internal`

2021-03-11 21:16 UTC, m4rs-mt commented on Src/ILGPU/Backends/PTX/PTXBackend.cs
> +                    debugSymbolsMode > DebugSymbolsMode.KernelSourceAnnotations
👍

2021-03-11 21:19 UTC, m4rs-mt commented on Src/ILGPU/Context.Builder.cs
> +                    (int)debugSymbolsMode);
QUESTION: What should happen if someone invokes `Assertions()` and then disables debug information via `DebugSymbols(Disabled)`?

2021-03-12 05:36 UTC, MoFtZ commented on Src/ILGPU/Backends/PTX/PTXArchitecture.cs
> +                architecture <= PTXArchitecture.SM_86;
Yes, I'm not sure the second check is necessary. As long as the architecture meets the minimum requirement, are there any restrictions on using future/unknown architectures?

2021-03-12 05:38 UTC, MoFtZ commented on Src/ILGPU/Backends/PTX/PTXArchitecture.cs
> +        public static bool TryGetArchitecture(
Should this also apply to `PTXInstructionSet`?

2021-03-12 05:54 UTC, MoFtZ commented on Src/ILGPU/Context.Builder.cs
> +                    (int)debugSymbolsMode);
Yes, it is an interesting problem. Some possible options are:
1. Last action wins, order of builder calls is important.
1. Runtime exception, informing the caller of a conflict.
1. Highest mode wins, as per this PR.

I'm not sure there is a "correct" answer here.

2021-03-12 11:02 UTC, m4rs-mt commented on Src/ILGPU/Backends/PTX/PTXArchitecture.cs
> +                architecture <= PTXArchitecture.SM_86;
Makes sense to me. I have removed the second check.

2021-03-12 11:43 UTC, m4rs-mt commented on Src/ILGPU/Backends/PTX/PTXArchitecture.cs
> +        public static bool TryGetArchitecture(
I think you are right: we should also rename `PTXInstructionSet` to `CudaInstructionSet` and move the `Runtime` namespace. This allows us to "keep private" the backend namespace.

2021-03-13 00:24 UTC, m4rs-mt commented on Src/ILGPU/Context.Builder.cs
> +                    (int)debugSymbolsMode);
Perhaps we should throw an `InvalidOperationException` indicating a conflicting situation.

2021-03-16 17:54 UTC, merged