Fixed invalid register/variable swaps.
m4rs-mt/ILGPU pull request #541
Opened 2021-07-17 00:17 UTC by m4rs-mt

This PR fixes a critical problem in the current `OpenCL` and `PTX` backends. When swapping views inside loops and then accessing them, it could happen that the actual swap operations were not compiled correctly. Although the IR itself represented the operations in a legal way, the backends swapped the registers/variables involved without introducing temporary swap targets. This PR fixes this critical problem by introducing "Phi intermediate values". This concept allows us to reason about Phi values that need to be stored in temporary locations without overwriting their values.

2021-07-17 01:32 UTC, MoFtZ requested changes
ISSUE: It looks like the new BasicLoop unit tests are failing on OpenCL.

The generated code fails to compile, complaining about undeclared variables. My guess is that the intermediate phi nodes are not being declared.

2021-07-17 11:57 UTC, m4rs-mt commented
@MoFtZ This was my bad as this PR was intended to be an initial draft, since the OpenCL version does not work at the moment 😃

2021-07-18 23:40 UTC, MoFtZ requested changes
ISSUE: The new BasicLoop unit tests are failing on OpenCL for O2.

Looks like an existing issue with `GenerateCode(AddressSpaceCast value)`.

2021-07-19 10:39 UTC, m4rs-mt commented
@MoFtZ In fact, this patch caused another issue that was already present in the code generation parts related to `AddressSpaceCast` values in the `CLBackend`.

2021-07-19 23:28 UTC, MoFtZ approved these changes

2021-07-20 07:59 UTC, merged