Fix zero-length subview behaviour
m4rs-mt/ILGPU pull request #550
Opened 2021-07-23 19:31 UTC by Joey9801

Currently if you attempt to create a subview that has zero length in at least one non-dense dimension, an exception gets thrown complaining about an index being out of range. It turns out that this comes from `ComputeBufferLength` returning a negative number.

The existing calculation in `ComputeBufferLength` is something like `stride.ComputeElementIndex(extent - IndexND.One) + 1`, ie it computes a value one past the end of the last element. When the extent is zero in at least one dimension however this behaves oddly, as the subtraction is non-saturating:
- If the only zero is in a dense dimension, it will return a positive non-zero number (not dangerously wrong, but more than required)
- If there is a zero in a non-dense dimension, it will return a negative number.  This is clearly wrong, and gets caught shortly afterwards when trying to create a subview of the BaseView.

This PR:
- Adds unit tests demonstrating the issue
- Adds some guards to the various `ComputeBufferLength` methods to fix this behaviour.
- Normalizes the implementation of `Stride2D.DenseX` such that it defers to the templated `ComputeBufferLength` methods like the other `Stride[2, 3]D.DenseAB` structs.

2021-07-23 22:58 UTC, m4rs-mt requested changes
Nice patch 👍 Yes, you are right that support for zero-length views has not been implemented properly. I think that this PR is a great extension to the current (sub)view API.

2021-07-23 22:58 UTC, m4rs-mt commented on Src/ILGPU/StrideTypes.tt
> -            /// <returns>The 3264-bit length of a required allocation.</returns>
Nice catch 🤓

2021-07-23 22:58 UTC, m4rs-mt commented on Src/ILGPU/StrideTypes.tt
> +            if (extent.<#= iName #> == 0) {
nit: Please removed the braces around the if statement.

2021-07-23 22:58 UTC, m4rs-mt commented on Src/ILGPU/StrideTypes.tt
> +            if (extent.<#= iName #> == 0L) {
nit: same here 🤓

2021-07-25 05:17 UTC, MoFtZ reviewed
QUESTION: Should we also deal with negative input values?

2021-07-25 05:17 UTC, MoFtZ commented on Src/ILGPU.Tests/ArrayViews.cs
> +        public void ArrayViewZeroLengthSubview1d()
MINOR: Follow existing naming convention - `SubView` and `1D`.
```suggestion
        public void ArrayViewZeroLengthSubView1D()
```

2021-07-25 05:17 UTC, MoFtZ commented on Src/ILGPU.Tests/ArrayViews.cs
> +        public void ArrayViewZeroLengthSubview2d()
```suggestion
        public void ArrayViewZeroLengthSubView2D()
```

2021-07-25 05:17 UTC, MoFtZ commented on Src/ILGPU.Tests/ArrayViews.cs
> +        public void ArrayViewZeroLengthSubview3d()
```suggestion
        public void ArrayViewZeroLengthSubView3D()
```

2021-07-26 12:19 UTC, Joey9801 commented
> QUESTION: Should we also deal with negative input values?

Aftter thinking about it for a bit, there are a few things that could be done for negative subview extents:
1. Alter the subview API to take unsigned extents, such that negative numbers are unrepresentable in the first place.
2. Throw runtime exceptions if there is a negative extent component
3. Actually try and support them in some meaningful way

There are a few interpretations of what 3. could mean:
- A negative extent component just shifts the start of the view backwards. Eg `[0, 1, 2, 3, 4, 5].SubView(3, -2) == [1, 2]`
- A negative extent component actually reverses the view in that axis. Eg `[0, 1, 2, 3, 4, 5].SubView(3, -2) == [2, 1]`. Could be trivially implemented with negative strides.

I think that of those options I would most favour 1., especially as v1.0 is still in beta so the public API is still mutable to a certain extent. To the best of my knowledge nobody is asking for any features that look like 3. Additionally it looks like implementing it could be fraught with odd edge cases and off-by-one errors, so it's by far my least favourite option.

2021-07-26 13:28 UTC, MoFtZ commented
> 1. Alter the subview API to take unsigned extents, such that negative numbers are unrepresentable in the first place.

This will be for @m4rs-mt to decide. Most of the APIs use signed integers, I'm guessing because it's CLS-compliant (?)

> 2. Throw runtime exceptions if there is a negative extent component

ILGPU does not currently support exceptions within the kernel. However, we can assert, which gets mapped to the accelerator-specific assert.

> 3. Actually try and support them in some meaningful way

I was thinking more of option 2 when I raised the question, but if we can come up with a meaningful API, then great. And yes, a separate PR sounds good to me.

2021-07-26 13:29 UTC, MoFtZ approved these changes

2021-07-26 20:21 UTC, m4rs-mt commented
> Most of the APIs use signed integers, I'm guessing because it's CLS-compliant (?)

@MoFtZ @Joey9801 Yes, you are right. This is to be CLS-compliant. I would prefer adding assertion checks to the code as @MoFtZ suggested.

2021-07-26 20:21 UTC, m4rs-mt approved these changes

2021-07-26 20:21 UTC, merged