Support static abstract interface members
m4rs-mt/ILGPU pull request #930
Opened 2023-02-13 21:37 UTC by lostmsu

This replaces specific generic math support introduced in 7bf55786f96a8912dcfd21b9e86e03c5e270fcd5 ( https://github.com/m4rs-mt/ILGPU/pull/898 )  with generic support for static abstract interface members.

Support is implemented using the constrained flag on the call instruction the same way it used to be done on virtual method calls. The call instruction with constrained flag set contains concrete type, that implements given interface, which makes it possible to find concrete method implementation to be called.

fixes https://github.com/m4rs-mt/ILGPU/issues/929

2023-02-14 01:02 UTC, MoFtZ requested changes
Thanks for this PR @lostmsu.

This is a much better implementation than the previous usage of reflection.

2023-02-14 04:12 UTC, lostmsu commented on Src/ILGPU/Frontend/CodeGenerator/Calls.cs
> +            var method = instruction.GetArgumentAs<MethodInfo>();
Fixed by adding a type test.

2023-02-14 04:13 UTC, lostmsu commented on Src/ILGPU/Frontend/CodeGenerator/Calls.cs
> +        private void MakeCall(ILInstruction instruction)
Added

2023-02-14 05:48 UTC, MoFtZ requested changes
hi @lostmsu.
Looks like the CI pipeline is [failing](https://github.com/m4rs-mt/ILGPU/actions/runs/4170303634/jobs/7219133033) because the copyright headers have not been updated.

The following command should update the necessary files:
`dotnet run --configuration=Release -p:TreatWarningsAsErrors=true --project Tools/CopyrightUpdateTool`,

2023-02-14 18:47 UTC, lostmsu commented
@MoFtZ hm, I don't seem to be able to reproduce unit test failures locally. Besides, before the copyright year change they were passing???

2023-02-14 20:36 UTC, MoFtZ commented
@lostmsu Looks like there is a new version of the .NET 7 SDK. CI pipeline used to work on `7.0.102`, and is now failing on `7.0.200`.

2023-02-15 19:01 UTC, lostmsu commented
Updated with the latest `master` that should have fixed the test failures.

2023-02-15 22:02 UTC, MoFtZ approved these changes

2023-02-16 10:56 UTC, m4rs-mt commented
Thanks a lot for you work on this issue 👍 !

2023-02-16 10:57 UTC, merged